spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.229.252:3306/zmmcktest?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: cktest
    
server:
  port: 8888
  
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
